#!/bin/bash

function error(){
	echo "$1"
	exit 1
}

if [ -z $1 ] ; then
	error "Usage: latc_x86_64 filepath"
fi

DIR=$(dirname "$0")
EXE="$DIR""/build/Main"
RUNTIME="${DIR}/lib/runtime.bc"
PROG="$1"

function compile() {
    path="$1"
    file="$(basename $path)"
    path_without_ext="${path%.lat}"
    file_llvm="${path_without_ext}.ll"
    tmp_file="${path_without_ext}_.bc"
    file_bc="${path_without_ext}.bc"
    "$EXE" "$1" 1> "$file_llvm"
    ret=$?
    if (( ret == 0 )) ; then
	llvm-as -o "${tmp_file}" "$file_llvm"
	if (( $? )) ; then
	    exit 1
	fi
	# echo "$file_bc"
	# echo "$tmp_file"
	# echo "$RUNTIME"
	llvm-link -o "$file_bc" "$tmp_file" "$RUNTIME"
	rm "$tmp_file"
	exit 0 
    else
	exit 1
    fi
}

compile "$1"
return "$?"
