#!/bin/bash

#!/bin/bash

function error(){
	echo "$1"
	exit 1
}

if [ -z $1 ] ; then
	error "Usage: latc_x86_64 filepath"
fi

DIR=$(dirname "$0")
EXE="$DIR""/build/Main"
PROG="$1"

function compile() {
    path="$1"
    file="$(basename $path)"
    path_without_ext="${path%.lat}"
    file_latte="${path_without_ext}.ll"
    "$EXE" "$1" 1>> "$file_latte"
    if (( "$?" == 0 )) ; then
	exit 0 
    else
	exit 1
    fi
}

compile "$1"
return "$?"
